### ISSUE TITLE
Publish on NPM?

### ISSUE THREAD

**Issue by guregu** [joewalnes/reconnecting-websocket#25]
There's a package.json but this seems to be unpublished.

**Comment by jeffscottward** [comment]
+1

**Comment by joewalnes** [comment]
This is an in-browser library designed for the HTML WebSocket API. It does not work with the Node equivalent.

**Comment by guregu** [comment]
It would work with something like Browerify or Webpack.

**Comment by jeffscottward** [comment]
2nd what Greg said. It's purely for pulling it down. Not an assumption to
work in node. I install everything from NPM. JQuery, D3, font awesome, you
name it.

**Comment by r3wt** [comment]
:-1: 

I hate having to hunt for packages on the npm site. its so slow.

**Comment by jeffscottward** [comment]
Thats like complaining that an airplane won't fly fast enough.

Remember what it was like hunting down the right jQuery plugin in the wild?

Lets get this on NPM pronto please.

**Comment by jeffscottward** [comment]
I cannot wait any longer for this. Will be forking and publishing my own, if/when you want the namespace back just let me know.

**Comment by agalazis** [comment]
@r3wt npm is awesome once you know what you want you don't even need to head to the website + it helps you to keep your dependencies tidy

**Comment by joewalnes** [comment]
The fork is a good solution. I prefer the model of downstream package maintainers as is common in other open source projects. I'm also not confident enough to maintain it upstream as I don't use this library via NPM.
