### ISSUE TITLE
reconnecting-websockets.d.ts does not compile

### ISSUE THREAD

**Issue by Fredicz** [joewalnes/reconnecting-websocket#44]
The reconnecting-websockets.d.ts does not compile anymore after the inclusion of **"public maxReconnectAttempts?: number;"** into the code. 
At least the TS 1.4.1 compiler complains with the following message:
**"error TS1112: A class member cannot be declared optional."**

**Comment by joewalnes** [comment]
I'm not familiar with typescript. Do you know the fix?

**Comment by Fredicz** [comment]
Thank you for the very fast fix! It works as expected.

**Comment by Fredicz** [comment]
The problem is actually not solved. Unfortunately my Reference.ts was still referencing the older version that did not include the error. That's why I thought it was resolved.

The ts compiler throws an error because of the question mark in line 39 of the reconnecting-websockets.d.ts (maxReconnectAttempts). It is illegal to use optional attributes in classes. They are only allowed in interfaces. Please change that. Since I use bower and cannot define the used version, I have to exclude reconnecting-websocket from the bower dependencies as long as it is not fixed properly.

**Comment by Fredicz** [comment]
I would suggest to use a Typescript interface instead of a Typescript class. That should fix the error and it should be possible since you are only describing the interface (or type).

**Comment by joewalnes** [comment]
This typescript file is making it harder to contribute to this project. Many contributions forget about it altogether, those that don't often don't know how to test it as they're not familiar with typescript.

My preference would be to remove it from this repository and allow other maintainers to keep it up to date in downstream forks if they want it.

Thoughts? Keep or delete?

/cc @drewnoakes

**Comment by Fredicz** [comment]
That would be fine for me.

**Comment by joewalnes** [comment]
I've just learned about https://github.com/borisyankov/DefinitelyTyped - a 3rd party repository of typescript definitions. If there's need for this file, it can be recreated there.

**Comment by Fredicz** [comment]
We actually use DefinetlyTyped. Thank you very much for solving the issue. Deletion of the file is perfect.

**Comment by drewnoakes** [comment]
Seems reasonable. Relying on Definitely Typed is a decent approach. Only
downside is the lack of versioning parity.

[via phone]
