### ISSUE TITLE
Can't reconnect in FF

### ISSUE THREAD

**Issue by aparmar** [joewalnes/reconnecting-websocket#5]
Hi - Have you noticed any issues in FF. I'm running FF21. During development, sometimes the browser is disconnected for a while and then it wouldn't reconnect when the server comes up. Error msg that keep repeaing are

    Firefox can't establish a connection to the server at <target>
    The connection to <target> was interrupted while the page was loading. 

Here is what I have tried so far
1. Refresh tab (button or Ctrl+F5): No changes. It somehow maintains state. And the above error comes up every couple of seconds
2. Closing the browser and restarting it: The tabs come back and it can now connect
3. Debugging: During debug, I can get the connection to go through if I debug with firebug

Any suggestions on where to start?

**Comment by AxelDelmas** [comment]
Shouldn't this issue be closed? It looks pretty outdated.
I was going through issues to see if I should consider using this lib, and not working on FF would be a no go. It seems it's not the case though

**Comment by aparmar** [comment]
We can close it. As you said, issue is old. I tried to trace it down (was a little difficult). All other browsers worked. I ended up using Chrome and creating a new "code" profile in FF. In FF, most of the time production sites didn't have an issue. It was mainly a development issue.
