### ISSUE TITLE
npm install?

### ISSUE THREAD

**Issue by let4be** [joewalnes/reconnecting-websocket#56]
Doesn't seem to have shorthand npm version
`npm i --save ReconnectingWebSocket`
`npm i --save reconnecting-websocket`
both fails

**Comment by joewalnes** [comment]
That is correct. It does not have an npm install.

Are you attempting to use it server-side from a node app or from a browser?

**Comment by Reggino** [comment]
Running into the same thing here, using it from node.

Why isn't it `npm publish`-ed?

**Comment by joewalnes** [comment]
No response from OP. Closing.
