### ISSUE TITLE
Push to NPM

### ISSUE THREAD

**Issue by marcelloma** [joewalnes/reconnecting-websocket#60]
Any plans to push this to NPM?

Thanks!

**Comment by wbecker** [comment]
+1

**Comment by jameslai** [comment]
+1

**Comment by endel** [comment]
Hi there, I've "forked" this project, and it's available on npm here: https://github.com/gamestdio/websocket.js

My implementation is way different, so maybe its behaviour is not exactly the same.

**Comment by zaynetro** [comment]
This library is on npm: https://www.npmjs.com/package/reconnectingwebsocket

**Comment by jbaudanza** [comment]
+1. This is on npm, but not the latest version.

**Comment by rohozhnikoff** [comment]
+1, push latest release

**Comment by bennycode** [comment]
@joewalnes, can you please push this library to npm because `npm install ReconnectingWebSocket` doesn't work.
