### ISSUE TITLE
Sending a message upon reconnect

### ISSUE THREAD

**Issue by stefan-reich** [joewalnes/reconnecting-websocket#91]
I'm surprised no one has asked for this. I need the ReconnectingWebSocket to send a message to the server when it reconnects, so the server knows what to stream.

Edit: Ah, I think I don't even need this. The ReconnectingWebSocket API sends me an onOpen event upon reconnect. And in the onOpen method, I send the necessary streaming command to the server anyway. It just works as advertised. You can test [here](http://smartbot.botcompany.de/dyn/1013377) if you like.

**Comment by stefan-reich** [comment]
I'm leaving it open for a bit for people to peruse

**Comment by nttoan26** [comment]
2 years are more than 'a bit', close it man
